### ISSUE TITLE
__invoke magic function not working

### ISSUE THREAD

**Issue by earllapura** [chadicus/slim-oauth2-routes#11]
Hi!

I have used your package in my project and it has worked. However, due to a server disk failure, I transferred my project to localhost and reconfigured it to a local database storage. When I accessed `/authorize`, the invoke seems to not work. I've put var_dumps at the functions, but it seems the var_dump inside the __invoke magic function did not execute, thus the authorization form did not appear.

What seems to be the problem?

Earl

**Comment by chadicus** [comment]
Do you have any sample code I could look at?  My first thought is that you did not register the route, but without seeing the implementation I'm not sure I can help.

**Comment by earllapura** [comment]
this is in my index.php

```
use Chadicus\Slim\OAuth2\Routes;
use Chadicus\Slim\OAuth2\Middleware;
use Chadicus\Slim\OAuth2\Http\MessageBridge;
use Slim\Slim;
use OAuth2\Server;
use OAuth2\Storage;
use OAuth2\GrantType;

#Dependencies autoload
require 'vendor/autoload.php';
#other dependencies here

#insert here dsn config
$storage = new OAuth2\Storage\Pdo(array('dsn' => $dsn, 'username' => $username, 'password' => $password));

// Pass a storage object or array of storage objects to the OAuth2 server class
$server = new OAuth2\Server($storage);

// "Authorization Code" grant type
$server->addGrantType(new OAuth2\GrantType\AuthorizationCode($storage));

$server->addGrantType(new OAuth2\GrantType\RefreshToken($storage, array(
    'always_issue_new_refresh_token' => true
)));

$app->config('templates.path', __DIR__ . '/vendor/chadicus/slim-oauth2-routes/templates');
Routes\Token::register($app, $server);
Routes\Authorize::register($app, $server);
Routes\ReceiveCode::register($app);

$authorization = new Middleware\Authorization($server);
$authorization->setApplication($app);

#my own route middleware classes
$routeauth = new AuthMiddleware\RouteAuthMiddleware($server);
$routeauth->setApplication($app);
$ratelimit = new AuthMiddleware\RateLimit('/');
$ratelimit->setApplication($app);

#my custom routes here
```

As you can see, I registered my routes. In your Authorize.php i just added in the __invoke() the line `$uid = $this->slim->request->post('user_id');` to get the user id and modified the `handleAuthorizeRequest` with `$this->server->handleAuthorizeRequest($request, $response, $authorized === 'yes', $uid);`. Is there something wrong with my code?

**Comment by earllapura** [comment]
I also ran this snippet to check if the routes are registered:

```
$routes = $app->router->getNamedRoutes();
foreach($routes as $route){ 
    echo "{$route->getName()} : {$route->getPattern()}<br/>"; 
}
```

The output is as follows:

```
token : /token
authorize : /authorize
receive-code : /receive-code
```

which means the slim-oauth2-routes are registered when the slim app is run. I think just have a problem in running the invoke function. I have PHP version 5.5.19.

**Comment by earllapura** [comment]
Eureka, I found the culprit! It seems the instantation of a custom middleware was trying to access memcached (installed in the damaged server) which was not installed in the localhost PHP environment.
